#!/bin/sh

# After suspend/resume, the card can sometimes get into a weird state
# resulting in Ollama not being able to detect it (error 999). This is
# a recommended fix. See:
# https://github.com/ollama/ollama/blob/main/docs/troubleshooting.md

sudo rmmod nvidia_uvm
sudo modprobe nvidia_uvm
