#!/bin/bash

# Run MusicGPT with proper local arguments

# This is a separate file so we can just ssh in and run this one thing
# for easy remote use.

# Get our paths
source `dirname $0`/ai_paths

if [ $HOSTNAME == "hiro" ]; then
    echo "Running on hiro, using that config."

    MUSICGPT_ARGS="--model small"
    
elif [ $HOSTNAME == "bluebox" ]; then
    echo "Running on bluebox, using that config."

    MUSICGPT_ARGS="--model medium"
else
    echo "Unknown host, using default config."
    SD_ARGS=""
fi

# export everything we're about to set because, from here on, it's
# configuration for what we are about to start.
set -a

# Args:
# --api - expose the API so other services can talk to it.
musicgpt ${MUSICGPT_ARGS} --ui-no-open
