#!/bin/bash

# Run Stable Diffusion with proper local arguments

# This is a separate file so we can just ssh in and run this one thing
# for easy remote use.

# Get our paths
source `dirname $0`/ai_paths

if [ $HOSTNAME == "hiro" ] ||
   [ $HOSTNAME == "bluebox" ]; then
    echo "Running on hiro/bluebox, using that config."
    SD_ARGS="--xformers --medvram"
else
    echo "Unknown host, using default config."
    SD_ARGS=""
fi

# export everything we're about to set because, from here on, it's
# configuration for what we are about to start.
set -a

# Different machines need different venvs because they have different incompatible dependencies.
# I save space by only having the one for the given host present.
venv_dir=${SD_BASE_DIR}/venv.${HOSTNAME}
# Args:
# --api - expose the API so other services can talk to it.
${SD_BASE_DIR}/webui.sh ${SD_ARGS} --api
