#!/bin/bash

# number of people talking in the video. This is almost always just
# me, so I'll change the script if that ever changes, rather than
# remember what I called the option, having to ask help, etc.
NUM_SPEAKERS=1

HF_TOKEN=`cat ~/.huggingface_token`

if [ $NUM_SPEAKERS -ne 1 ]; then
    # For some reason, it seems to work better when you add 1 to the max
    # number of speakers.
    MAX_SPEAKERS=$(($NUM_SPEAKERS + 1))
   
    echo "Enabling diarization for ${NUM_SPEAKERS} speakers".
    SPEAKERS_ARGS="--min_speakers ${NUM_SPEAKERS} --max_speakers ${MAX_SPEAKERS} --diarize --hf_token ${HF_TOKEN}"
fi

VENV_DIR=/home/matt/storage1/ai/whisperx/venv
MODEL_DIR=/home/matt/storage1/ai/whisperx/models
MODEL=large-v3

# Note: float16 doesn't work with CPU
CPU_ARGS="--device cpu --threads 32 --compute_type int8"

# int8 doesn't work on 5070 TI. See:
# https://github.com/SYSTRAN/faster-whisper/issues/1260
GPU_ARGS="--device cuda --compute_type float16 --batch_size 8"

VIDEO=$1

SRT="${VIDEO%.*}".srt



source ${VENV_DIR}/bin/activate

whisperx --model ${MODEL} ${GPU_ARGS} --model_dir ${MODEL_DIR} --output_format srt \
         --verbose False --language en --print_progress True ${SPEAKERS_ARGS} $VIDEO

deactivate
